server:
  port: 8080
spring:
  webflux:
    base-path: /account
  application:
    name: account
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/accountdb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health,info,conditions
app:
  build:
    version: 1.0.0
  support:
    contact:
      name: Account Service Support Team
      email: support@account.service.local
    message: Welcome to Account Service. We are here to help!
    oncallsupport:
      - "+1-800-123-4567"
      - "+1-800-234-5678"
      - "+1-800-345-6789"
