apiVersion: v2
name: eazybank-observability
description: Observability stack for EazyBank (Prometheus, Grafana, Loki, Tempo, OTel Collector, Alloy)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - prometheus
  - grafana
  - loki
  - tempo
  - opentelemetry
  - observability
home: https://github.com/sharanggupta/eazybank
maintainers:
  - name: Sharang Gupta
