{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eazybank-service.postgresql.fullname" . }}
  labels:
    {{- include "eazybank-service.postgresql.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.credentials.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.credentials.password | quote }}
{{- end }}
