{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eazybank-service.postgresql.fullname" . }}
  labels:
    {{- include "eazybank-service.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "eazybank-service.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
