image:
  tag: "__IMAGE_TAG__"

app:
  spring:
    profiles: dev
  build:
    version: 0.0.1
  env:
    SERVICES_ACCOUNT_URL: "http://account:8080"
    SERVICES_CARD_URL: "http://card:9000"
    SERVICES_LOAN_URL: "http://loan:8090"
