server:
  port: 8090
  servlet:
    context-path: /loan
spring:
  application:
    name: loan
  datasource:
    url: jdbc:postgresql://localhost:5432/loandb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health,info,conditions
app:
  build:
    version: 1.0.0
  support:
    contact:
      name: Loan Service Support Team
      email: support@loan.service.local
    message: Welcome to Loan Service. We are here to help!
    oncallsupport:
      - "+1-800-123-4567"
      - "+1-800-234-5678"
      - "+1-800-345-6789"