server:
  port: 8090
spring:
  application:
    name: loan
  webflux:
    base-path: /loan
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/loandb}
    username: ${SPRING_R2DBC_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_R2DBC_PASSWORD:${POSTGRES_PASSWORD:postgres}}
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
app:
  build:
    version: 1.0.0
  support:
    contact:
      name: Loan Service Support Team
      email: support@loan.service.local
    message: Welcome to Loan Service. We are here to help!
    oncallsupport:
      - "+1-800-123-4567"
      - "+1-800-234-5678"
      - "+1-800-345-6789"