# Loan service - Production environment - Application configuration
image:
  tag: "__IMAGE_TAG__"

app:
  spring:
    profiles: prod
  datasource:
    username: postgres
    password: "__DB_PASSWORD__"
  support:
    contactName: Loan Production Support
    contactEmail: support@loan.eazybank.com
    message: Welcome to EazyBank Loan Service
  env: {}

postgresql:
  credentials:
    username: postgres
    password: "__DB_PASSWORD__"
