# Loan service - Production environment - Application configuration
image:
  tag: "__IMAGE_TAG__"

app:
  spring:
    profiles: prod
  build:
    version: 0.0.1
  datasource:
    username: postgres
    password: "__DB_PASSWORD__"
  support:
    contactName: Loan Production Support
    contactEmail: support@loan.eazybank.com
    contactNumber: "+1-555-0301"
    message: Welcome to EazyBank Loan Service
  env:
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "0.1"
    MANAGEMENT_OTLP_TRACING_ENDPOINT: "${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318/v1/traces}"

postgresql:
  credentials:
    username: postgres
    password: "__DB_PASSWORD__"
