image:
  tag: "__IMAGE_TAG__"

app:
  spring:
    profiles: dev
  build:
    version: 0.0.1
  env:
    SERVICES_ACCOUNT_URL: "http://account:8080"
    SERVICES_CARD_URL: "http://card:9000"
    SERVICES_LOAN_URL: "http://loan:8090"
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://otel-collector:4318/v1/traces"
