# Account service - Dev environment - Application configuration
image:
  tag: latest

app:
  spring:
    profiles: dev
  build:
    version: 0.0.1
  datasource:
    username: postgres
    password: "__DB_PASSWORD__"
  support:
    contactName: Account Dev Support
    contactEmail: dev-support@account.service.local
    contactNumber: "+1-555-0001"
    message: Welcome to EazyBank Account Service (Dev)
  env:
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://otel-collector:4318/v1/traces"

postgresql:
  credentials:
    username: postgres
    password: "__DB_PASSWORD__"
