# Account service - Dev environment - Application configuration
image:
  tag: latest

app:
  spring:
    profiles: dev
  datasource:
    username: postgres
    password: "__DB_PASSWORD__"
  support:
    contactName: Account Dev Support
    contactEmail: dev-support@account.service.local
    message: Welcome to EazyBank Account Service (Dev)
  env: {}

postgresql:
  credentials:
    username: postgres
    password: "__DB_PASSWORD__"
