{{- if and .Values.enabled .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.grafana.admin.password | b64enc | quote }}
{{- end }}
