{{- if and .Values.enabled .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app: loki
  {{- with .Values.loki.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.loki.service.type }}
  ports:
  - port: {{ .Values.loki.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: loki
{{- end }}
