{{- if and .Values.enabled .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app: otel-collector
  {{- with .Values.otelCollector.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.otelCollector.service.type }}
  ports:
  - port: {{ .Values.otelCollector.service.ports.otlpHttp }}
    targetPort: otlp
    protocol: TCP
    name: otlp
  - port: {{ .Values.otelCollector.service.ports.prometheus }}
    targetPort: prometheus
    protocol: TCP
    name: prometheus
  selector:
    app: otel-collector
{{- end }}
