{{- if .Values.otelCollector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability-chart.fullname" . }}-otel-collector
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app: otel-collector
spec:
  replicas: {{ .Values.otelCollector.replicas }}
  selector:
    matchLabels:
      app: otel-collector
      {{- include "observability-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: otel-collector
        {{- include "observability-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "observability-sa-name" . }}
      containers:
      - name: otel-collector
        image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
        imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
        ports:
        - name: otlp-http
          containerPort: {{ .Values.otelCollector.service.otlpHttp.port }}
          protocol: TCP
        - name: metrics
          containerPort: {{ .Values.otelCollector.service.prometheusMetrics.port }}
          protocol: TCP
        env:
        - name: GOGC
          value: "80"
        resources:
          requests:
            cpu: {{ .Values.otelCollector.resources.requests.cpu }}
            memory: {{ .Values.otelCollector.resources.requests.memory }}
          limits:
            cpu: {{ .Values.otelCollector.resources.limits.cpu }}
            memory: {{ .Values.otelCollector.resources.limits.memory }}
        volumeMounts:
        - name: otel-config
          mountPath: /etc/otel
      volumes:
      - name: otel-config
        configMap:
          name: {{ include "observability-chart.fullname" . }}-otel-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-chart.fullname" . }}-otel-collector
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app: otel-collector
spec:
  type: ClusterIP
  ports:
  - name: otlp-http
    port: {{ .Values.otelCollector.service.otlpHttp.port }}
    targetPort: otlp-http
    protocol: TCP
  - name: metrics
    port: {{ .Values.otelCollector.service.prometheusMetrics.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    app: otel-collector
    {{- include "observability-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-chart.fullname" . }}-otel-config
  namespace: {{ .Release.Namespace | quote }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:{{ .Values.otelCollector.service.otlpHttp.port }}

    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 512

    exporters:
      prometheus:
        endpoint: "0.0.0.0:{{ .Values.otelCollector.service.prometheusMetrics.port }}"
        namespace: eazybank

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
{{- end }}
