{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability-sa-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-labels" . | nindent 4 }}
{{- end }}
