{{- if and .Values.enabled .Values.tempo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app: tempo
spec:
  type: {{ .Values.tempo.service.type }}
  ports:
  - port: {{ .Values.tempo.service.ports.otlp }}
    targetPort: otlp
    protocol: TCP
    name: otlp
  - port: {{ .Values.tempo.service.ports.prometheus }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: tempo
{{- end }}
