# Loan service - Staging environment - Application configuration
image:
  tag: "__IMAGE_TAG__"

app:
  spring:
    profiles: staging
  build:
    version: 0.0.1
  datasource:
    username: postgres
    password: "__DB_PASSWORD__"
  support:
    contactName: Loan Staging Support
    contactEmail: staging-support@loan.service.local
    contactNumber: "+1-555-0300"
    message: Welcome to EazyBank Loan Service (Staging)
  env:
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "0.1"
    MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://otel-collector:4318/v1/traces"

postgresql:
  credentials:
    username: postgres
    password: "__DB_PASSWORD__"
