# Loan service - Staging environment - Application configuration
image:
  tag: "__IMAGE_TAG__"

app:
  spring:
    profiles: staging
  datasource:
    username: postgres
    password: "__DB_PASSWORD__"
  support:
    contactName: Loan Staging Support
    contactEmail: staging-support@loan.service.local
    message: Welcome to EazyBank Loan Service (Staging)
  env: {}

postgresql:
  credentials:
    username: postgres
    password: "__DB_PASSWORD__"
