# Loan service - Dev environment - Application configuration
image:
  tag: latest

app:
  spring:
    profiles: dev
  build:
    version: 0.0.1
  datasource:
    username: postgres
    password: "__DB_PASSWORD__"
  support:
    contactName: Loan Dev Support
    contactEmail: dev-support@loan.service.local
    contactNumber: "+1-555-0003"
    message: Welcome to EazyBank Loan Service (Dev)
  observability:
    enabled: true
    samplingRate: "1.0"
    otlpEndpoint: "http://otel-collector.otel.svc.cluster.local:4318"

postgresql:
  credentials:
    username: postgres
    password: "__DB_PASSWORD__"
