{{- if .Values.k8s.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eazybank-service.fullname" . }}
  labels:
    {{- include "eazybank-service.labels" . | nindent 4 }}
  {{- with .Values.k8s.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.k8s.ingress.className }}
  ingressClassName: {{ .Values.k8s.ingress.className }}
  {{- end }}
  {{- if .Values.k8s.ingress.tls }}
  tls:
    {{- range .Values.k8s.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.k8s.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.k8s.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "eazybank-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
