apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eazybank-service.fullname" . }}
  labels:
    {{- include "eazybank-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.app.datasource.password | quote }}
