{{- if or .Values.app.datasource.url .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eazybank-service.fullname" . }}
  labels:
    {{- include "eazybank-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_R2DBC_PASSWORD: {{ .Values.app.datasource.password | quote }}
{{- end -}}
