{{- if .Values.k8s.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eazybank-service.serviceAccountName" . }}
  labels:
    {{- include "eazybank-service.labels" . | nindent 4 }}
  {{- with .Values.k8s.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
