{{- if .Values.observability.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "eazybank-service.fullname" . }}
  labels:
    {{- include "eazybank-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "eazybank-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ if .Values.service.contextPath }}{{ .Values.service.contextPath }}{{ end }}/actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
