apiVersion: v1
kind: Service
metadata:
  name: {{ include "eazybank-service.fullname" . }}
  labels:
    {{- include "eazybank-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.k8s.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.k8s.service.type "NodePort") .Values.k8s.service.nodePort }}
      nodePort: {{ .Values.k8s.service.nodePort }}
      {{- end }}
  selector:
    {{- include "eazybank-service.selectorLabels" . | nindent 4 }}
