management:
  tracing:
    sampling:
      probability: 0.1  # 10% sampling in production

logging:
  level:
    root: INFO
    dev.sharanggupta: INFO
    org.springframework.cloud.gateway: INFO
    io.github.resilience4j: INFO